server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ski_bar?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    com.ski_bar: debug
  file:
    path: log/blog-dev.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/g5619/mapper/xml/**.xml
  type-aliases-package: com.g5619.entity
#  global-config:
#    db-config:
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不加步骤2的注解)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


mail:
  host: smtp.qq.com #邮件服务器地址
  port: 465 #端口号
  username: 
  password: 
  default-encoding: UTF-8 #默认编码格式
  properties:
    mail:
      debug: true #启动debug调试
      smtp:
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory #SSL连接配置

